apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  VIDEO_QUEUE: "video"
  MP3_QUEUE: "mp3"