apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
stringData:
  MYSQL_HOST: mysql
  MYSQL_USER: auth_user
  MYSQL_PASSWORD: Auth123
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
  PLACEHOLDER: nothing
