# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_HOST: mysql
  MYSQL_USER: auth_user
  MYSQL_PASSWORD: Auth123
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: admin123  # Eksik olan bu değer